#ifndef SPHINCS_PLUS_PARAMS_H
#define SPHINCS_PLUS_PARAMS_H

#define SPHINCS_PLUS_SEEDBYTES 32
#define SPHINCS_PLUS_CRHBYTES 48
#define SPHINCS_PLUS_N 256
#define SPHINCS_PLUS_Q 8380417
#define SPHINCS_PLUS_QBITS 23
#define SPHINCS_PLUS_ROOT_OF_UNITY 1753
#define SPHINCS_PLUS_D 14
#define SPHINCS_PLUS_GAMMA1 ((SPHINCS_PLUS_Q - 1)/16)
#define SPHINCS_PLUS_GAMMA2 (SPHINCS_PLUS_GAMMA1/2)
#define SPHINCS_PLUS_ALPHA (2*SPHINCS_PLUS_GAMMA2)

#endif
